name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install fyne-cross
        run: go install ://github.com

      - name: Run Fyne-Cross Android Build
        run: |
          # Сборка из корня проекта, где теперь лежат все файлы
          fyne-cross android --pull=false -no-cache --app-id com.frost.photosync.v10 --name PhotoSyncMobileAuto .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhotoSync-Android-APK
          path: ./fyne-cross/dist/android/PhotoSyncMobileAuto.apk
