name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fyne Android Build
        uses: lucasbento/fyne-action@v1
        with:
          os: android
          app-id: com.frost.photosync.v10
          name: PhotoSyncMobileAuto
