name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib libgl1-mesa-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false # Отключаем кэш, так как у нас нет файла go.sum

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Fyne CLI
        run: go install fyne.io/fyne/v2/cmd/fyne@latest

      - name: Download Android NDK
        run: |
          cd $ANDROID_HOME
          sdkmanager --install "ndk;25.1.8937393"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.1.8937393" >> $GITHUB_ENV

      - name: Build APK
        run: |
          go mod tidy # Сервер сам сгенерирует недостающий файл go.sum
          fyne package -os android -appID com.frost.photosync.v10 -name "PhotoSyncMobileAuto" -icon Icon.png

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhotoSync-Android-APK
          path: ./PhotoSyncMobileAuto.apk
